apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ci-cd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-ci-cd-demo
  template:
    metadata:
      labels:
        app: node-ci-cd-demo
    spec:
      containers:
        - name: node-ci-cd-demo
          image: ${DOCKER_USERNAME}/node-ci-cd-demo:${SEMAPHORE_WORKFLOW_ID}
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "$PORT"

---
apiVersion: v1
kind: Service
metadata:
  name: node-ci-cd-demo
spec:
  selector:
    app: node-ci-cd-demo
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
